name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  sqflite_common_ffi_web: '>=0.1.0-dev.1'
  get_it: ^7.7.0
  pluto_grid: ^8.0.0
  horizontal_data_table: ^4.3.1
  syncfusion_flutter_datagrid: ^25.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
    - assets/